build: false

environment:
  CONAN_RUN_TESTS: 1
  PYTHON: "C:\\Python37"

  matrix:
    - MINGW_CONFIGURATIONS: "9@x86_64@seh@posix"

install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
